// This code was autogenerated with `dbus-codegen-rust `, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopPortalGlobalShortcuts {
    fn create_session(&self, options: arg::PropMap) -> Result<dbus::Path<'static>, dbus::Error>;
    fn bind_shortcuts(&self, session_handle: dbus::Path, shortcuts: Vec<(&str, arg::PropMap,)>, parent_window: &str, options: arg::PropMap) -> Result<dbus::Path<'static>, dbus::Error>;
    fn list_shortcuts(&self, session_handle: dbus::Path, options: arg::PropMap) -> Result<dbus::Path<'static>, dbus::Error>;
    fn configure_shortcuts(&self, session_handle: dbus::Path, parent_window: &str, options: arg::PropMap) -> Result<(), dbus::Error>;
    fn version(&self) -> Result<u32, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopPortalGlobalShortcutsActivated {
    pub session_handle: dbus::Path<'static>,
    pub shortcut_id: String,
    pub timestamp: u64,
    pub options: arg::PropMap,
}

impl arg::AppendAll for OrgFreedesktopPortalGlobalShortcutsActivated {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.session_handle, i);
        arg::RefArg::append(&self.shortcut_id, i);
        arg::RefArg::append(&self.timestamp, i);
        arg::RefArg::append(&self.options, i);
    }
}

impl arg::ReadAll for OrgFreedesktopPortalGlobalShortcutsActivated {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopPortalGlobalShortcutsActivated {
            session_handle: i.read()?,
            shortcut_id: i.read()?,
            timestamp: i.read()?,
            options: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopPortalGlobalShortcutsActivated {
    const NAME: &'static str = "Activated";
    const INTERFACE: &'static str = "org.freedesktop.portal.GlobalShortcuts";
}

#[derive(Debug)]
pub struct OrgFreedesktopPortalGlobalShortcutsDeactivated {
    pub session_handle: dbus::Path<'static>,
    pub shortcut_id: String,
    pub timestamp: u64,
    pub options: arg::PropMap,
}

impl arg::AppendAll for OrgFreedesktopPortalGlobalShortcutsDeactivated {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.session_handle, i);
        arg::RefArg::append(&self.shortcut_id, i);
        arg::RefArg::append(&self.timestamp, i);
        arg::RefArg::append(&self.options, i);
    }
}

impl arg::ReadAll for OrgFreedesktopPortalGlobalShortcutsDeactivated {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopPortalGlobalShortcutsDeactivated {
            session_handle: i.read()?,
            shortcut_id: i.read()?,
            timestamp: i.read()?,
            options: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopPortalGlobalShortcutsDeactivated {
    const NAME: &'static str = "Deactivated";
    const INTERFACE: &'static str = "org.freedesktop.portal.GlobalShortcuts";
}

#[derive(Debug)]
pub struct OrgFreedesktopPortalGlobalShortcutsShortcutsChanged {
    pub session_handle: dbus::Path<'static>,
    pub shortcuts: Vec<(String, arg::PropMap,)>,
}

impl arg::AppendAll for OrgFreedesktopPortalGlobalShortcutsShortcutsChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.session_handle, i);
        arg::RefArg::append(&self.shortcuts, i);
    }
}

impl arg::ReadAll for OrgFreedesktopPortalGlobalShortcutsShortcutsChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopPortalGlobalShortcutsShortcutsChanged {
            session_handle: i.read()?,
            shortcuts: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopPortalGlobalShortcutsShortcutsChanged {
    const NAME: &'static str = "ShortcutsChanged";
    const INTERFACE: &'static str = "org.freedesktop.portal.GlobalShortcuts";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopPortalGlobalShortcuts for blocking::Proxy<'a, C> {

    fn create_session(&self, options: arg::PropMap) -> Result<dbus::Path<'static>, dbus::Error> {
        self.method_call("org.freedesktop.portal.GlobalShortcuts", "CreateSession", (options, ))
            .and_then(|r: (dbus::Path<'static>, )| Ok(r.0, ))
    }

    fn bind_shortcuts(&self, session_handle: dbus::Path, shortcuts: Vec<(&str, arg::PropMap,)>, parent_window: &str, options: arg::PropMap) -> Result<dbus::Path<'static>, dbus::Error> {
        self.method_call("org.freedesktop.portal.GlobalShortcuts", "BindShortcuts", (session_handle, shortcuts, parent_window, options, ))
            .and_then(|r: (dbus::Path<'static>, )| Ok(r.0, ))
    }

    fn list_shortcuts(&self, session_handle: dbus::Path, options: arg::PropMap) -> Result<dbus::Path<'static>, dbus::Error> {
        self.method_call("org.freedesktop.portal.GlobalShortcuts", "ListShortcuts", (session_handle, options, ))
            .and_then(|r: (dbus::Path<'static>, )| Ok(r.0, ))
    }

    fn configure_shortcuts(&self, session_handle: dbus::Path, parent_window: &str, options: arg::PropMap) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.portal.GlobalShortcuts", "ConfigureShortcuts", (session_handle, parent_window, options, ))
    }

    fn version(&self) -> Result<u32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.freedesktop.portal.GlobalShortcuts", "version")
    }
}
