// This code was autogenerated with `dbus-codegen-rust `, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopHostPortalRegistry {
    fn register(&self, app_id: &str, options: arg::PropMap) -> Result<(), dbus::Error>;
    fn version(&self) -> Result<u32, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopHostPortalRegistry for blocking::Proxy<'a, C> {

    fn register(&self, app_id: &str, options: arg::PropMap) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.host.portal.Registry", "Register", (app_id, options, ))
    }

    fn version(&self) -> Result<u32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.freedesktop.host.portal.Registry", "version")
    }
}
